owner: Linesmerrill
repo: police-cad-status

sites:
  - name: Police CAD Frontend
    url: https://www.linespolice-cad.com
  - name: Police CAD API
    url: https://police-cad-app-api-bc6d659b60b3.herokuapp.com

status-website:
  cname: status.linespolice-cad.com
  name: Lines Police CAD Status
  introTitle: "**Lines Police CAD** service status and uptime monitor."
  introMessage: This page shows real-time availability and response time data for Lines Police CAD services. Powered by [Upptime](https://github.com/upptime/upptime).
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: Lines Police CAD
      href: https://www.linespolice-cad.com
    - title: Discord Support
      href: https://discord.gg/Y9ytW2ZMp4
    - title: Report a Bug
      href: https://github.com/Linesmerrill/police-cad/issues/new?assignees=&labels=&template=bug_report.md&title=
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
